ALTER TABLE tokens
    ADD COLUMN IF NOT EXISTS expiry_date TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE tokens
    ALTER COLUMN expiry_date DROP DEFAULT;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;