ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS city VARCHAR (50);
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS street VARCHAR (50);
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS house VARCHAR (10);
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS apartment VARCHAR (10);
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS address_comment VARCHAR (200);
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS delivery_method VARCHAR (20) NOT NULL DEFAULT 'DELIVERY';
ALTER TABLE orders DROP COLUMN IF EXISTS address;