ALTER TABLE users
    ALTER COLUMN password DROP NOT NULL;
ALTER TABLE users
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users
    ADD COLUMN verification_token VARCHAR(255);